name: Bug Report
description: Report a bug or issue with the extension
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the bug?
      placeholder: Describe the issue you're experiencing...
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Extension Version
      description: What version of the extension are you using?
      placeholder: e.g., v1.0.0
    validations:
      required: true
  - type: input
    id: immich-version
    attributes:
      label: Immich Server Version
      description: What version of Immich is your server running?
      placeholder: e.g., v1.115.0
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: e.g., Chrome, Edge, Brave
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here or paste image URLs...
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might help
      placeholder: Error messages, console logs, etc.
